server:
  port: 8761

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://Employee
          predicates:
            - Path=/employee/**

        - id: auth-service
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

